spring.application.name=ecommerce

# Configuración de logs
logging.level.root=INFO
logging.level.org.hibernate=DEBUG
logging.level.org.springframework=DEBUG

spring.datasource.url=jdbc:oracle:thin:@ecommercecloudnative_high?TNS_ADMIN=../EcommerceCloudNative/Wallet_EcommerceCloudNative

spring.datasource.username=admin
spring.datasource.password=CloudNative_123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Configuración del pool de conexiones HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

spring.security.user.name=Admin
spring.security.user.password=CloudNative_123

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLong
jwt.expiration=86400000