spring.application.name=ecommerce-ventas-k1

# Server configuration
server.port=8091

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka-1:9092,kafka-2:9093,kafka-3:9094}
kafka.topic.ventas=ventas

# Database configuration
spring.datasource.url=jdbc:oracle:thin:@ecommercecloudnative_high?TNS_ADMIN=/app/Wallet_EcommerceCloudNative
spring.datasource.username=admin
spring.datasource.password=CloudNative_123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=false

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLong
jwt.expiration=86400000

# Logging
logging.level.root=INFO
logging.file.name=/app/logs/ventas-k1.log